// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTtdH8fQultxB33bQzpkSfmID6pcea7es',
    appId: '1:593396642309:web:883ec23875cb1ad95be26c',
    messagingSenderId: '593396642309',
    projectId: 'al-maequl',
    authDomain: 'al-maequl.firebaseapp.com',
    storageBucket: 'al-maequl.appspot.com',
    measurementId: 'G-L49S59VH7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3NfomzUz4KV3_Y9WRvxYqRm95lpkpl2k',
    appId: '1:593396642309:android:7431c9caeb50998e5be26c',
    messagingSenderId: '593396642309',
    projectId: 'al-maequl',
    storageBucket: 'al-maequl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb8y4q0seH9EY_tAiZIAhzLnxFEy-C5qw',
    appId: '1:593396642309:ios:9eceda9573394be95be26c',
    messagingSenderId: '593396642309',
    projectId: 'al-maequl',
    storageBucket: 'al-maequl.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb8y4q0seH9EY_tAiZIAhzLnxFEy-C5qw',
    appId: '1:593396642309:ios:e7674218f96fb4f05be26c',
    messagingSenderId: '593396642309',
    projectId: 'al-maequl',
    storageBucket: 'al-maequl.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseEcommerce.RunnerTests',
  );
}
